### ISSUE TITLE
Performance implications of PKBDF2-HMAC-SHA* in Erlang

### ISSUE THREAD

**Issue by NelsonVides** [exograd/erl-pkcs#1]
I want to raise something that I raise everywhere where I see an implementation of pbkdf2 in erlang: your algorithm is linear in memory consumption, no matter what you do. It also applies `4*N` compression functions of the underlying hash algorithm, where `N` is the iteration count. Here's a NIF implementation that consumes constant memory time, applies `2+2*N` compression functions, and has all the timeslicing and scheduling artillery of an erlang nif: https://github.com/esl/fast_pbkdf2
I got very verbose explaining this last time here: https://github.com/riverrun/pbkdf2_elixir/issues/11

PS: I got this repo of yours from the latest erlang-mailing-lists questions :)

**Comment by gearnode** [comment]
The RFC algorithm is constructed like this, and yes, for sure, it's possible
to optimize it. I do not consider slow performance as an issue for this
kind of algorithms as I don't try to brute-force a leaked database.

And the optimization you propose comes with a lot of drawback for me:
- The algorithm is more complex
- The algorithm is less extendable
- Having to deal with a NIF in the VM

The idea behind the optimization is exciting, but performance is
not a real issue for me. I don't plan to change this.

Thanks for sharing!

**Comment by NelsonVides** [comment]
I wouldn't try to brute-force a DB with a nif either, that'd only work with dedicated GPUs or FPGAs. It's a matter of firing other defence mechanisms before a server gets DoS: if any part of the program gets susceptible to calculating PBKDF2 on request (a server on authenticating clients is a classic, but not only), the Erlang code is tremendously suboptimal. Similarly, I don't see any overhead with dealing with a NIF, it's "out-of-the-box". It's not even a dirty nif, so it can run on a regular scheduler on any kind of VM including very very old versions.

The algorithm being more complex, well, quite so with the compression reusing and the NIF re-scheduling 😕 But it'd argue it's a fair case, PBKDF2 is an algorithm that is explicitly written without any place for modifications apart from the underlying hash function. Extensible, here's the thing: the NIF code would make it virtually impossible to add SHA3 to the mix, but I'd argue SHA3 doesn't make any better with PBKDF2, PBKDF2 is so much designed to fit Merkle-Damgard constructions like SHA1 and SHA2 hashes.

Ultimately, Erlang code is more "maintenable", I'd just argue this is a case so much tailored to C to be worth the hassle. Nevertheless, thanks for considering the option 🙂
